name: travel_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4
  image_picker: ^1.2.1
  camera: ^0.10.5
  gal: ^1.1.1
  screenshot: ^2.1.0
  intl: ^0.19.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.0
  geolocator: ^12.0.0
  geocoding: ^2.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
